spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: x0tAvsFhU8

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: mapper/*.xml

logging:
  level:
    com.example.demo.mapper: debug

server:
  servlet:
    context-path: /demo
  port: 8088