spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: x0tAvsFhU8

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: mapper/*.xml

logging:
  level:
    com.example.demo.mapper: debug

  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yy-MM-dd HH:mm:ss}}){cyan} %clr(%-40.40logger{39}){cyan}%n%clr(${LOG_LEVEL_PATTERN:%-5p}) %m${LOG_EXCEPTION_CONVERSION_WORD:%n%wEx}%n}"
server:
  servlet:
    context-path: /demo
  port: 8088